<?xml version="1.0"?>
<robot name="base_plate" xmlns:xacro="http://ros.org/wiki/xacro">

<link name="base_plate">
    <visual>
    <origin xyz="0 0 -0.01"/>
      <geometry>
          <box size="1.0 1.0 0.02"/>
      </geometry>
      <material name="base_plate_white">
          <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
    <origin xyz="0 0 -0.01"/>
      <geometry>
        <box size="1.0 1.0 0.02"/>
      </geometry>
    </collision>
    </link>
    <joint name="base_joint" type="fixed">
      <parent link="base_link" />
      <child link = "base_plate" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
    </robot>

<!-- <xacro:macro name="cube" params="">

<xacro:property name="size" value="0.1"/>

  <link name="cube_link">
    <inertial>
      <origin xyz="${size/2.0} ${size/2.0} ${size/2.0}" />
      <mass value="1.0" />
      <inertia  ixx="1.0" ixy="0.0"  ixz="1.0"  iyy="1.0"  iyz="1.0"  izz="1.0" />
    </inertial>
    <visual>
      <origin xyz="${size/2.0} ${size/2.0} ${size/2.0}"/>
      <geometry>
        <box size="${size} ${size} ${size}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${size/2.0} ${size/2.0} ${size/2.0}"/>
      <geometry>
        <box size="${size} ${size} ${size}" />
      </geometry>
    </collision>
  </link>
  
  <gazebo reference="cube">
  <material>Gazebo/Blue</material>
  </gazebo>


  </xacro:macro>
  
    <joint name="cube_joint" type="fixed">
      <parent link="base_link"/>
      <child link="cube_link"/>
      <origin xyz="0.2 0.2 0.2" rpy="0 0.0 0.0"/>
  </joint>

-->