<?xml version="1.0"?>
<robot name="cube" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:arg name="size" default="0.1"/>
<xacro:arg name="origin_xyz" default="0.2 0.2 0.2"/>
<xacro:arg name="origin_rpy" default="0 0 0"/>
<xacro:property name="size" value="0.1" />

<link name="cube0">
    <visual>
    <origin xyz="${size/2.0} ${size/2.0} ${size/2.0}"/>
      <geometry>
          <box size="${size} ${size} ${size}"/>
      </geometry>
      <material name="cube_blue">
          <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
    <origin xyz="${size/2.0} ${size/2.0} ${size/2.0}"/>
      <geometry>
        <box size="${size} ${size} ${size}"/>
      </geometry>
    </collision>
    </link>
    <joint name="cube0_joint" type="fixed">
      <parent link="base_link" />
      <child link = "cube0" />
      <origin xyz="$(arg origin_xyz)" rpy="$(arg origin_rpy)" />
    </joint>
    </robot>

<!-- <xacro:macro name="cube" params="">

<xacro:property name="size" value="0.1"/>

  <link name="cube_link">
    <inertial>
      <origin xyz="${size/2.0} ${size/2.0} ${size/2.0}" />
      <mass value="1.0" />
      <inertia  ixx="1.0" ixy="0.0"  ixz="1.0"  iyy="1.0"  iyz="1.0"  izz="1.0" />
    </inertial>
    <visual>
      <origin xyz="${size/2.0} ${size/2.0} ${size/2.0}"/>
      <geometry>
        <box size="${size} ${size} ${size}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${size/2.0} ${size/2.0} ${size/2.0}"/>
      <geometry>
        <box size="${size} ${size} ${size}" />
      </geometry>
    </collision>
  </link>
  
  <gazebo reference="cube">
  <material>Gazebo/Blue</material>
  </gazebo>


  </xacro:macro>
  
    <joint name="cube_joint" type="fixed">
      <parent link="base_link"/>
      <child link="cube_link"/>
      <origin xyz="0.2 0.2 0.2" rpy="0 0.0 0.0"/>
  </joint>

-->