# This is an example filter config for tracked vehicle Absolem from Czech Technical University's
# VRAS team. The robot is equipped with a Realsense D435.
# The field of view of the sensor can only capture a few links, so the `only_links` parameter is set
# to increase performance. Also, the `filter/keep_clouds_organized` parameter is important here to
# retain the 2D structure of the RGBD camera output.
cloud_filter_chain:
  - name: robot_body_filter
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
      frames/fixed: 'base_link'
      frames/sensor: ''
      #frames/filtering: frames/fixed
      #frames/output: frames/filtering
      filter/keep_clouds_organized: False
      filter/do_clipping: False
      filter/do_contains_test: True
      filter/do_shadow_test: False
      filter/model_pose_update_interval: 0.0
      sensor/point_by_point: False
      sensor/min_distance: 0.0
      sensor/max_distance: 100.0
      body_model/inflation/scale: 2.0 #1.07
      body_model/inflation/padding: 0.01
      body_model/robot_description_param: '/robot_description'
      only_links: ['base_link_inertia','shoulder_link','upper_arm_link', 'forearm_link','wrist_1_link','wrist_2_link','wrist_3_link','rg2_body_link','rg2_eef_link','base_link']
      transforms/buffer_length: 15.0
      transforms/timeout/reachable: 0.2
      transforms/timeout/unreachable: 0.2
      bounding_sphere/compute: False
      bounding_box/compute: False
      oriented_bounding_box/compute: True
      local_bounding_box/compute: False
      debug/pcl/inside: False
      debug/pcl/clip: False
      debug/pcl/shadow: False
      debug/marker/contains: False
      debug/marker/shadow: False
      debug/marker/bounding_box: True
